#!/bin/sh

# tcc is a fast compiler
CC=cc
which tcc > /dev/null && CC=tcc

# sacrify a little compilation time for better performances
CFLAGS="-O3"

if [ $# -lt 2 ]; then
    echo 'syntax: $0 img1.png img2.png ... "espression"'
    echo '        between 1 and 4 input images'
    echo '        "-" for std intput'
    exit
fi

NBINPUT=$(($# - 1))
INPUT=""
for I in $( seq $NBINPUT); do
    INPUT="$INPUT $1"
    shift
done
LAMBDA="$1"

# debug option
set -x

$CC $CFLAGS -D__NBINPUT=$NBINPUT -D__LAMBDA="$LAMBDA" \
    cclambda.c io_png.c -lpng -o cclambda.run
exec ./cclambda.run $INPUT
